name: build
on:
  - workflow_dispatch

jobs:
  build:
    # Don't run when commit is being pushed from Github Actions to prevent endless recursion.
    if: ${{ !(github.event_name == 'push' && github.event.head_commit.author.name == 'github-actions[bot]') }}
    name: ${{ matrix.os }} ${{ matrix.instructions }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
        instructions:
          - avx2
          - avx

    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
          GPTJ_AVX2: ${{ matrix.instructions == 'avx2' && 'ON' || 'OFF' }}
        run: |
          mkdir out
          git clone --recurse-submodules https://github.com/marella/gptj.cpp
          cp CMakeLists-ggml.txt gptj.cpp/ggml/src/CMakeLists.txt
          cd gptj.cpp
          
          mkdir build
          cd build
          cmake .. -DGPTJ_AVX2=$GPTJ_AVX2
          cmake --build . --config Release
      - if: startsWith(runner.os, 'Linux')
        run: |
          cp gptj.cpp/build/src/libgptj.so out
          cp gptj.cpp/build/ggml/src/libggml.so out
      - if: startsWith(runner.os, 'macOS')
        run: |
          cp gptj.cpp/build/src/libgptj.dylib out
          cp gptj.cpp/build/ggml/src/libggml.dylib out
      - if: startsWith(runner.os, 'Windows')
        run: |
          cp gptj.cpp\build\bin\Release\gptj.dll out
          cp gptj.cpp\build\bin\Release\ggml.dll out
      - env:
          GPTJ_DIR: ${{ matrix.instructions }}
        run: |
          mv out $GPTJ_DIR
          mkdir out
          mv $GPTJ_DIR out
      - uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: out
          if-no-files-found: error

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/download-artifact@v3
        with:
          name: libraries
          path: lib
      - uses: git-actions/set-user@v1
      - name: Save
        run: |
          ls lib/*
          git add lib
          git commit -m 'Auto Build'
          # git push
