name: cmake
on:
  - workflow_dispatch

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir out
          git clone --recurse-submodules https://github.com/marella/gptj.cpp
          cd gptj.cpp
          
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
      - if: startsWith(runner.os, 'Linux')
        run: |
          cp gptj.cpp/build/src/libgptj.so out
          cp gptj.cpp/build/ggml/src/libggml.so out
      - if: startsWith(runner.os, 'macOS')
        run: |
          cp gptj.cpp/build/src/libgptj.dylib out
          cp gptj.cpp/build/ggml/src/libggml.dylib out
      - if: startsWith(runner.os, 'Windows')
        run: |
          cp gptj.cpp\build\bin\Release\gptj.dll out
          cp gptj.cpp\build\bin\Release\ggml.dll out
      - uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: out
          if-no-files-found: error

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/download-artifact@v3
        with:
          name: libraries
          path: lib
      - uses: git-actions/set-user@v1
      - name: Save
        run: |
          git add --all
          git commit -m 'Auto Build'
          git push
